version: '3.6'
services:

  #######################################################################
  ####################  astixlimited.com  ################################
  #######################################################################


  #PHP Service
  astixlimited_com_web:
    build:
      context: .
      dockerfile: ./astixlimited.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "astixlimited_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/astixlimited.com/
    volumes:
      - ./astixlimited.com/:/var/www/astixlimited.com/
      - ./astixlimited.com/docker/php-fpm/:/usr/local/etc/php/conf.d/


  #######################################################################
  ####################  marathonexpert.com  ################################
  #######################################################################


  #PHP Service
  marathonexpert_com_web:
    build:
      context: .
      dockerfile: ./marathonexpert.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "marathonexpert_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/marathonexpert.com/
    volumes:
      - ./marathonexpert.com/:/var/www/marathonexpert.com/
      - ./marathonexpert.com/docker/php-fpm/:/usr/local/etc/php/conf.d/


  #######################################################################
  ####################  yourdailyworkouts.com  ################################
  #######################################################################

  #PHP Service
  yourdailyworkouts_com_web:
    build:
      context: .
      dockerfile: ./yourdailyworkouts.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "yourdailyworkouts_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/yourdailyworkouts.com/
    volumes:
      - ./yourdailyworkouts.com/:/var/www/yourdailyworkouts.com/
      - ./yourdailyworkouts.com/docker/php-fpm/:/usr/local/etc/php/conf.d/


  #######################################################################
  ####################  yourfitnesstrainer365.com  ################################
  #######################################################################

  #PHP Service
  yourfitnesstrainer365_com_web:
    build:
      context: .
      dockerfile: ./yourfitnesstrainer365.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "yourfitnesstrainer365_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/yourfitnesstrainer365.com/
    volumes:
      - ./yourfitnesstrainer365.com/:/var/www/yourfitnesstrainer365.com/
      - ./yourfitnesstrainer365.com/docker/php-fpm/:/usr/local/etc/php/conf.d/


  #######################################################################
  ####################  fillingyoga.com  ################################
  #######################################################################

  #PHP Service
  fillingyoga_com_web:
    build:
      context: .
      dockerfile: ./fillingyoga.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "fillingyoga_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/fillingyoga.com/
    volumes:
      - ./fillingyoga.com/:/var/www/fillingyoga.com/
      - ./fillingyoga.com/docker/php-fpm/:/usr/local/etc/php/conf.d/

  #######################################################################
  #################### powerliftguru.com ################################
  #######################################################################

  #PHP Service
  powerliftguru_com_web:
    build:
      context: .
      dockerfile: ./powerliftguru.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "powerliftguru_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/powerliftguru.com/
    volumes:
      - ./powerliftguru.com/:/var/www/powerliftguru.com/
      - ./powerliftguru.com/docker/php-fpm/:/usr/local/etc/php/conf.d/

  #######################################################################
  #######################   Services   ##################################
  #######################################################################

  db:
    image: mysql/mysql-server:5.7
    volumes:
      - "database:/var/lib/mysql"
      - "./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    command: [
      # "--general_log=1",
      # "--general_log_file=/var/lib/mysql/general_log.log",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci",
      "--default-storage-engine=innodb",
      "--innodb-file-per-table",
      "--explicit_defaults_for_timestamp=1",
      "--default-time-zone=+00:00"
    ]

#Volumes
volumes:
  database:

