version: '3'
services:

  #######################################################################
  #################### powerliftguru.com ################################
  #######################################################################

  #NodeJS Service
  powerliftguru_com_nodejs:
    build:
      context: .
      dockerfile: ./powerliftguru.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-powerliftguru-nodejs"
    depends_on:
      - powerliftguru_com_web
    volumes:
      - ./powerliftguru.com/:/var/www/
    networks:
      - app-network


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - powerliftguru_com_web
      - fillingyoga_com_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./powerliftguru.com/:/var/www/powerliftguru.com/
      - ./powerliftguru.com/docker/nginx/local.conf:/etc/nginx/conf.d/powerliftguru.conf

      - ./fillingyoga.com/:/var/www/fillingyoga.com/
      - ./fillingyoga.com/docker/nginx/local.conf:/etc/nginx/conf.d/fillingyoga.conf
    networks:
      - app-network

#  ###############################################
#  ##############   API CONTAINERS  ##############
#  ###############################################

  #PHP Service
  app_api:
    build:
      context: .
      dockerfile: ./api/docker/php-fpm/Dockerfile.local
    image: digitalocean.com/php
    container_name: "${DOCKER_PREFIX_API}-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db_api
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./api/:/var/www
      - ./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver_api:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX_API}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - app_api
    ports:
      - "3000:80"
#      - "443:443"
    volumes:
      - ./api/:/var/www
      - ./api/docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #MySQL Service
  db_api:
    image: mysql:5.7.22
    container_name: "${DOCKER_PREFIX_API}-db"
    restart: unless-stopped
    tty: true
    ports:
      - "4406:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_API}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_API}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_api_data:/var/lib/mysql/
      - ./api/docker/mysql/:/etc/mysql/
    networks:
      - app-network

  nodejs_api:
    build:
      context: .
      dockerfile: ./api/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX_API}-nodejs"
    depends_on:
      - app_api
    volumes:
      - ./api/:/var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  db_api_data:
    driver: local
