version: '3'
services:

  #######################################################################
  ##################  astixlimited.com  ########################
  #######################################################################

  #NodeJS Service
  astixlimited_com_nodejs:
    build:
      context: .
      dockerfile: ./astixlimited.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-astixlimited-nodejs"
    depends_on:
      - astixlimited_com_web
    volumes:
      - ./astixlimited.com/:/var/www/
    networks:
      - app-network


  #######################################################################
  ##################  yourfitnesstrainer365.com  ########################
  #######################################################################

  #NodeJS Service
  yourfitnesstrainer365_com_nodejs:
    build:
      context: .
      dockerfile: ./yourfitnesstrainer365.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-yourfitnesstrainer365-nodejs"
    depends_on:
      - yourfitnesstrainer365_com_web
    volumes:
      - ./yourfitnesstrainer365.com/:/var/www/
    networks:
      - app-network

  #######################################################################
  ####################  yourdailyworkouts.com  ################################
  #######################################################################

  #NodeJS Service
  yourdailyworkouts_com_nodejs:
    build:
      context: .
      dockerfile: ./yourdailyworkouts.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-yourdailyworkouts-nodejs"
    depends_on:
      - yourdailyworkouts_com_web
    volumes:
      - ./yourdailyworkouts.com/:/var/www/
    networks:
      - app-network

  #######################################################################
  ####################  fillingyoga.com  ################################
  #######################################################################

  #NodeJS Service
  fillingyoga_com_nodejs:
    build:
      context: .
      dockerfile: ./fillingyoga.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-fillingyoga-nodejs"
    depends_on:
      - fillingyoga_com_web
    volumes:
      - ./fillingyoga.com/:/var/www/
    networks:
      - app-network

  #######################################################################
  ###################  marathonexpert.com  ##############################
  #######################################################################

  #NodeJS Service
  marathonexpert_com_nodejs:
    build:
      context: .
      dockerfile: ./marathonexpert.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-marathonexpert-nodejs"
    depends_on:
      - marathonexpert_com_web
    volumes:
      - ./marathonexpert.com/:/var/www/
    networks:
      - app-network

  #######################################################################
  #################### powerliftguru.com ################################
  #######################################################################

  #NodeJS Service
  powerliftguru_com_nodejs:
    build:
      context: .
      dockerfile: ./powerliftguru.com/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-powerliftguru-nodejs"
    depends_on:
      - powerliftguru_com_web
    volumes:
      - ./powerliftguru.com/:/var/www/
    networks:
      - app-network


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - powerliftguru_com_web
      - fillingyoga_com_web
      - marathonexpert_com_web
      - yourdailyworkouts_com_web
      - yourfitnesstrainer365_com_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./astixlimited.com/:/var/www/astixlimited.com/
      - ./astixlimited.com/docker/nginx/local.conf:/etc/nginx/conf.d/astixlimited.conf

      - ./powerliftguru.com/:/var/www/powerliftguru.com/
      - ./powerliftguru.com/docker/nginx/local.conf:/etc/nginx/conf.d/powerliftguru.conf

      - ./fillingyoga.com/:/var/www/fillingyoga.com/
      - ./fillingyoga.com/docker/nginx/local.conf:/etc/nginx/conf.d/fillingyoga.conf

      - ./marathonexpert.com/:/var/www/marathonexpert.com/
      - ./marathonexpert.com/docker/nginx/local.conf:/etc/nginx/conf.d/marathonexpert.conf

      - ./yourdailyworkouts.com/:/var/www/yourdailyworkouts.com/
      - ./yourdailyworkouts.com/docker/nginx/local.conf:/etc/nginx/conf.d/yourdailyworkouts.conf

      - ./yourfitnesstrainer365.com/:/var/www/yourfitnesstrainer365.com/
      - ./yourfitnesstrainer365.com/docker/nginx/local.conf:/etc/nginx/conf.d/yourfitnesstrainer365.conf

      - ./descriptors/:/var/www/descriptors/
    networks:
      - app-network

  #######################################################################
  #######################   Services   ##################################
  #######################################################################

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    #    command: --init-file /etc/mysql/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/:/etc/mysql/
    networks:
      - app-network

#  ###############################################
#  ##############   API CONTAINERS  ##############
#  ###############################################

  #PHP Service
  app_api:
    build:
      context: .
      dockerfile: ./api/docker/php-fpm/Dockerfile.local
    image: digitalocean.com/php
    container_name: "${DOCKER_PREFIX_API}-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db_api
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./api/:/var/www
      - ./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver_api:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX_API}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - app_api
    ports:
      - "3000:80"
#      - "443:443"
    volumes:
      - ./api/:/var/www
      - ./api/docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #MySQL Service
  db_api:
    image: mysql:5.7.22
    container_name: "${DOCKER_PREFIX_API}-db"
    restart: unless-stopped
    tty: true
    ports:
      - "4406:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_API}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_API}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_api_data:/var/lib/mysql/
      - ./api/docker/mysql/:/etc/mysql/
    networks:
      - app-network

  nodejs_api:
    build:
      context: .
      dockerfile: ./api/docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX_API}-nodejs"
    depends_on:
      - app_api
    volumes:
      - ./api/:/var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  db_api_data:
    driver: local
