version: '3'
services:

  #######################################################################
  ####################  astixlimited.com  ################################
  #######################################################################


  #PHP Service
  astixlimited_com_web:
    build:
      context: .
      dockerfile: ./astixlimited.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "astixlimited_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/astixlimited.com/
    volumes:
      - ./astixlimited.com/:/var/www/astixlimited.com/
      - ./astixlimited.com/docker/php-fpm/:/usr/local/etc/php/conf.d/
    networks:
      - app-network


  #######################################################################
  ####################  marathonexpert.com  ################################
  #######################################################################


  #PHP Service
  marathonexpert_com_web:
    build:
      context: .
      dockerfile: ./marathonexpert.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "marathonexpert_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/marathonexpert.com/
    volumes:
      - ./marathonexpert.com/:/var/www/marathonexpert.com/
      - ./marathonexpert.com/docker/php-fpm/:/usr/local/etc/php/conf.d/
    networks:
      - app-network


  #######################################################################
  ####################  yourdailyworkouts.com  ################################
  #######################################################################

  #PHP Service
  yourdailyworkouts_com_web:
    build:
      context: .
      dockerfile: ./yourdailyworkouts.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "yourdailyworkouts_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/yourdailyworkouts.com/
    volumes:
      - ./yourdailyworkouts.com/:/var/www/yourdailyworkouts.com/
      - ./yourdailyworkouts.com/docker/php-fpm/:/usr/local/etc/php/conf.d/
    networks:
      - app-network


  #######################################################################
  ####################  yourfitnesstrainer365.com  ################################
  #######################################################################

  #PHP Service
  yourfitnesstrainer365_com_web:
    build:
      context: .
      dockerfile: ./yourfitnesstrainer365.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "yourfitnesstrainer365_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/yourfitnesstrainer365.com/
    volumes:
      - ./yourfitnesstrainer365.com/:/var/www/yourfitnesstrainer365.com/
      - ./yourfitnesstrainer365.com/docker/php-fpm/:/usr/local/etc/php/conf.d/
    networks:
      - app-network


  #######################################################################
  ####################  fillingyoga.com  ################################
  #######################################################################

  #PHP Service
  fillingyoga_com_web:
    build:
      context: .
      dockerfile: ./fillingyoga.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "fillingyoga_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/fillingyoga.com/
    volumes:
      - ./fillingyoga.com/:/var/www/fillingyoga.com/
      - ./fillingyoga.com/docker/php-fpm/:/usr/local/etc/php/conf.d/
    networks:
      - app-network

  #######################################################################
  #################### powerliftguru.com ################################
  #######################################################################

  #PHP Service
  powerliftguru_com_web:
    build:
      context: .
      dockerfile: ./powerliftguru.com/docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "powerliftguru_com-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/powerliftguru.com/
    volumes:
      - ./powerliftguru.com/:/var/www/powerliftguru.com/
      - ./powerliftguru.com/docker/php-fpm/:/usr/local/etc/php/conf.d/
    networks:
      - app-network

  #######################################################################
  #######################   Services   ##################################
  #######################################################################

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    #    command: --init-file /etc/mysql/init.sql
    #    ports:
    #      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/:/etc/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata: