version: '3.6'
services:

  #######################################################################
  ####################  astixlimited.com  ################################
  #######################################################################

  astixlimited_com_web:
    build: docker/php-fpm
    depends_on:
      - db
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
    working_dir: /var/www/astixlimited.com
    volumes:
      - "./astixlimited.com/:/var/www/astixlimited.com/"
      - "./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./.composer/:/www/.composer"


  #######################################################################
  ####################  marathonexpert.com  ################################
  #######################################################################

  marathonexpert_com_web:
    build: docker/php-fpm
    depends_on:
      - db
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
    working_dir: /var/www/marathonexpert.com/
    volumes:
      - "./marathonexpert.com/:/var/www/marathonexpert.com/"
      - "./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./.composer/:/www/.composer"

  #######################################################################
  ####################  yourdailyworkouts.com  ################################
  #######################################################################

  yourdailyworkouts_com_web:
    build: docker/php-fpm
    depends_on:
      - db
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
    working_dir: /var/www/yourdailyworkouts.com/
    volumes:
      - "./yourdailyworkouts.com/:/var/www/yourdailyworkouts.com/"
      - "./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./.composer/:/www/.composer"

  #######################################################################
  ####################  yourfitnesstrainer365.com  ################################
  #######################################################################

  yourfitnesstrainer365_com_web:
    build: docker/php-fpm
    depends_on:
      - db
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
    working_dir: /var/www/yourfitnesstrainer365.com/
    volumes:
      - "./yourfitnesstrainer365.com/:/var/www/yourfitnesstrainer365.com/"
      - "./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./.composer/:/www/.composer"

  #######################################################################
  ####################  fillingyoga.com  ################################
  #######################################################################

  fillingyoga_com_web:
    build: docker/php-fpm
    depends_on:
      - db
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
    working_dir: /var/www/fillingyoga.com/
    volumes:
      - "./fillingyoga.com/:/var/www/fillingyoga.com/"
      - "./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./.composer/:/www/.composer"


  #######################################################################
  #################### powerliftguru.com ################################
  #######################################################################

  powerliftguru_com_web:
    build: docker/php-fpm
    depends_on:
      - db
    environment:
      - "DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}"
    working_dir: /var/www/powerliftguru.com/
    volumes:
      - "./powerliftguru.com/:/var/www/powerliftguru.com/"
      - "./api/docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./.composer/:/www/.composer"

  #######################################################################
  #######################   Services   ##################################
  #######################################################################

  db:
    image: mysql/mysql-server:5.7
    volumes:
      - "database:/var/lib/mysql"
      - "./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    command: [
      # "--general_log=1",
      # "--general_log_file=/var/lib/mysql/general_log.log",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci",
      "--default-storage-engine=innodb",
      "--innodb-file-per-table",
      "--explicit_defaults_for_timestamp=1",
      "--default-time-zone=+00:00"
    ]

#Volumes
volumes:
  database:
